# Generated by Django 2.0 on 2017-12-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vainpick', '0003_auto_20171204_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPickStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_count', models.IntegerField(default=0)),
                ('hero1', models.CharField(max_length=40)),
                ('hero2', models.CharField(max_length=40)),
                ('hero3', models.CharField(max_length=40)),
                ('win_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
