# Generated by Django 2.0 on 2017-12-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vainpick', '0004_heropickstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropickstat',
            name='hero1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='heropickstat',
            name='hero2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='heropickstat',
            name='hero3',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
