# Generated by Django 2.0 on 2017-12-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vainpick', '0005_auto_20171204_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropickstat',
            name='win_rate_str',
            field=models.CharField(default='no', max_length=5),
            preserve_default=False,
        ),
    ]
