# Generated by Django 2.0 on 2017-12-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vainpick', '0006_heropickstat_win_rate_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropickstat',
            name='win_rate_str',
            field=models.CharField(default='0.0', max_length=5),
        ),
    ]
