# Generated by Django 2.0 on 2017-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vainpick', '0007_auto_20171204_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='hero1',
            new_name='left_hero1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='hero2',
            new_name='left_hero2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='hero3',
            new_name='left_hero3',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='win',
            new_name='left_win',
        ),
        migrations.AddField(
            model_name='match',
            name='right_hero1',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='right_hero2',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='right_hero3',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='right_win',
            field=models.BooleanField(default=False),
        ),
    ]
